// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: cron/cron.proto

package cron

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddClearMsgJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationID string `protobuf:"bytes,1,opt,name=conversationID,proto3" json:"conversationID,omitempty"`
	CronCycle      int32  `protobuf:"varint,3,opt,name=cronCycle,proto3" json:"cronCycle,omitempty"`
}

func (x *AddClearMsgJobReq) Reset() {
	*x = AddClearMsgJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_cron_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddClearMsgJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClearMsgJobReq) ProtoMessage() {}

func (x *AddClearMsgJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_cron_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClearMsgJobReq.ProtoReflect.Descriptor instead.
func (*AddClearMsgJobReq) Descriptor() ([]byte, []int) {
	return file_cron_cron_proto_rawDescGZIP(), []int{0}
}

func (x *AddClearMsgJobReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *AddClearMsgJobReq) GetCronCycle() int32 {
	if x != nil {
		return x.CronCycle
	}
	return 0
}

type AddClearMsgJobResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddClearMsgJobResp) Reset() {
	*x = AddClearMsgJobResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_cron_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddClearMsgJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClearMsgJobResp) ProtoMessage() {}

func (x *AddClearMsgJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_cron_cron_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClearMsgJobResp.ProtoReflect.Descriptor instead.
func (*AddClearMsgJobResp) Descriptor() ([]byte, []int) {
	return file_cron_cron_proto_rawDescGZIP(), []int{1}
}

var File_cron_cron_proto protoreflect.FileDescriptor

var file_cron_cron_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x72, 0x6f, 0x6e, 0x2f, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x63, 0x72, 0x6f, 0x6e, 0x22, 0x59, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x4d, 0x73, 0x67, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x6f, 0x6e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x72, 0x6f, 0x6e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x22,
	0x14, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4d, 0x73, 0x67, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x32, 0xc7, 0x01, 0x0a, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x12, 0x5d,
	0x0a, 0x0e, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4d, 0x73, 0x67, 0x4a, 0x6f, 0x62,
	0x12, 0x24, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4d, 0x73, 0x67,
	0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x4d, 0x73, 0x67, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x12, 0x60, 0x0a,
	0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4d, 0x73, 0x67, 0x4a,
	0x6f, 0x62, 0x12, 0x24, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4d,
	0x73, 0x67, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49,
	0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x41, 0x64, 0x64,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x4d, 0x73, 0x67, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4f, 0x70,
	0x65, 0x6e, 0x49, 0x4d, 0x53, 0x44, 0x4b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x63, 0x72, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cron_cron_proto_rawDescOnce sync.Once
	file_cron_cron_proto_rawDescData = file_cron_cron_proto_rawDesc
)

func file_cron_cron_proto_rawDescGZIP() []byte {
	file_cron_cron_proto_rawDescOnce.Do(func() {
		file_cron_cron_proto_rawDescData = protoimpl.X.CompressGZIP(file_cron_cron_proto_rawDescData)
	})
	return file_cron_cron_proto_rawDescData
}

var file_cron_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cron_cron_proto_goTypes = []interface{}{
	(*AddClearMsgJobReq)(nil),  // 0: OpenIMServer.cron.AddClearMsgJobReq
	(*AddClearMsgJobResp)(nil), // 1: OpenIMServer.cron.AddClearMsgJobResp
}
var file_cron_cron_proto_depIdxs = []int32{
	0, // 0: OpenIMServer.cron.cron.AddClearMsgJob:input_type -> OpenIMServer.cron.AddClearMsgJobReq
	0, // 1: OpenIMServer.cron.cron.RemoveClearMsgJob:input_type -> OpenIMServer.cron.AddClearMsgJobReq
	1, // 2: OpenIMServer.cron.cron.AddClearMsgJob:output_type -> OpenIMServer.cron.AddClearMsgJobResp
	1, // 3: OpenIMServer.cron.cron.RemoveClearMsgJob:output_type -> OpenIMServer.cron.AddClearMsgJobResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cron_cron_proto_init() }
func file_cron_cron_proto_init() {
	if File_cron_cron_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cron_cron_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddClearMsgJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_cron_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddClearMsgJobResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cron_cron_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cron_cron_proto_goTypes,
		DependencyIndexes: file_cron_cron_proto_depIdxs,
		MessageInfos:      file_cron_cron_proto_msgTypes,
	}.Build()
	File_cron_cron_proto = out.File
	file_cron_cron_proto_rawDesc = nil
	file_cron_cron_proto_goTypes = nil
	file_cron_cron_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CronClient is the client API for Cron service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CronClient interface {
	AddClearMsgJob(ctx context.Context, in *AddClearMsgJobReq, opts ...grpc.CallOption) (*AddClearMsgJobResp, error)
	RemoveClearMsgJob(ctx context.Context, in *AddClearMsgJobReq, opts ...grpc.CallOption) (*AddClearMsgJobResp, error)
}

type cronClient struct {
	cc grpc.ClientConnInterface
}

func NewCronClient(cc grpc.ClientConnInterface) CronClient {
	return &cronClient{cc}
}

func (c *cronClient) AddClearMsgJob(ctx context.Context, in *AddClearMsgJobReq, opts ...grpc.CallOption) (*AddClearMsgJobResp, error) {
	out := new(AddClearMsgJobResp)
	err := c.cc.Invoke(ctx, "/OpenIMServer.cron.cron/AddClearMsgJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) RemoveClearMsgJob(ctx context.Context, in *AddClearMsgJobReq, opts ...grpc.CallOption) (*AddClearMsgJobResp, error) {
	out := new(AddClearMsgJobResp)
	err := c.cc.Invoke(ctx, "/OpenIMServer.cron.cron/RemoveClearMsgJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronServer is the server API for Cron service.
type CronServer interface {
	AddClearMsgJob(context.Context, *AddClearMsgJobReq) (*AddClearMsgJobResp, error)
	RemoveClearMsgJob(context.Context, *AddClearMsgJobReq) (*AddClearMsgJobResp, error)
}

// UnimplementedCronServer can be embedded to have forward compatible implementations.
type UnimplementedCronServer struct {
}

func (*UnimplementedCronServer) AddClearMsgJob(context.Context, *AddClearMsgJobReq) (*AddClearMsgJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddClearMsgJob not implemented")
}
func (*UnimplementedCronServer) RemoveClearMsgJob(context.Context, *AddClearMsgJobReq) (*AddClearMsgJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveClearMsgJob not implemented")
}

func RegisterCronServer(s *grpc.Server, srv CronServer) {
	s.RegisterService(&_Cron_serviceDesc, srv)
}

func _Cron_AddClearMsgJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddClearMsgJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).AddClearMsgJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenIMServer.cron.cron/AddClearMsgJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).AddClearMsgJob(ctx, req.(*AddClearMsgJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_RemoveClearMsgJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddClearMsgJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).RemoveClearMsgJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenIMServer.cron.cron/RemoveClearMsgJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).RemoveClearMsgJob(ctx, req.(*AddClearMsgJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cron_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OpenIMServer.cron.cron",
	HandlerType: (*CronServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddClearMsgJob",
			Handler:    _Cron_AddClearMsgJob_Handler,
		},
		{
			MethodName: "RemoveClearMsgJob",
			Handler:    _Cron_RemoveClearMsgJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cron/cron.proto",
}
