// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: club/club.proto

package club

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateServerReq) Reset() {
	*x = CreateServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerReq) ProtoMessage() {}

func (x *CreateServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerReq.ProtoReflect.Descriptor instead.
func (*CreateServerReq) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{0}
}

type CreateServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateServerResp) Reset() {
	*x = CreateServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerResp) ProtoMessage() {}

func (x *CreateServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerResp.ProtoReflect.Descriptor instead.
func (*CreateServerResp) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{1}
}

var File_club_club_proto protoreflect.FileDescriptor

var file_club_club_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6c, 0x75, 0x62, 0x2f, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x63, 0x6c, 0x75, 0x62, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x32, 0x5f, 0x0a, 0x04, 0x63,
	0x6c, 0x75, 0x62, 0x12, 0x57, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x24, 0x5a, 0x22,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4f, 0x70, 0x65, 0x6e, 0x49,
	0x4d, 0x53, 0x44, 0x4b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6c,
	0x75, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_club_club_proto_rawDescOnce sync.Once
	file_club_club_proto_rawDescData = file_club_club_proto_rawDesc
)

func file_club_club_proto_rawDescGZIP() []byte {
	file_club_club_proto_rawDescOnce.Do(func() {
		file_club_club_proto_rawDescData = protoimpl.X.CompressGZIP(file_club_club_proto_rawDescData)
	})
	return file_club_club_proto_rawDescData
}

var file_club_club_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_club_club_proto_goTypes = []interface{}{
	(*CreateServerReq)(nil),  // 0: OpenIMServer.club.CreateServerReq
	(*CreateServerResp)(nil), // 1: OpenIMServer.club.CreateServerResp
}
var file_club_club_proto_depIdxs = []int32{
	0, // 0: OpenIMServer.club.club.createServer:input_type -> OpenIMServer.club.CreateServerReq
	1, // 1: OpenIMServer.club.club.createServer:output_type -> OpenIMServer.club.CreateServerResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_club_club_proto_init() }
func file_club_club_proto_init() {
	if File_club_club_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_club_club_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_club_club_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_club_club_proto_goTypes,
		DependencyIndexes: file_club_club_proto_depIdxs,
		MessageInfos:      file_club_club_proto_msgTypes,
	}.Build()
	File_club_club_proto = out.File
	file_club_club_proto_rawDesc = nil
	file_club_club_proto_goTypes = nil
	file_club_club_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClubClient is the client API for Club service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClubClient interface {
	// 创建部落
	CreateServer(ctx context.Context, in *CreateServerReq, opts ...grpc.CallOption) (*CreateServerResp, error)
}

type clubClient struct {
	cc grpc.ClientConnInterface
}

func NewClubClient(cc grpc.ClientConnInterface) ClubClient {
	return &clubClient{cc}
}

func (c *clubClient) CreateServer(ctx context.Context, in *CreateServerReq, opts ...grpc.CallOption) (*CreateServerResp, error) {
	out := new(CreateServerResp)
	err := c.cc.Invoke(ctx, "/OpenIMServer.club.club/createServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClubServer is the server API for Club service.
type ClubServer interface {
	// 创建部落
	CreateServer(context.Context, *CreateServerReq) (*CreateServerResp, error)
}

// UnimplementedClubServer can be embedded to have forward compatible implementations.
type UnimplementedClubServer struct {
}

func (*UnimplementedClubServer) CreateServer(context.Context, *CreateServerReq) (*CreateServerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServer not implemented")
}

func RegisterClubServer(s *grpc.Server, srv ClubServer) {
	s.RegisterService(&_Club_serviceDesc, srv)
}

func _Club_CreateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).CreateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenIMServer.club.club/CreateServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).CreateServer(ctx, req.(*CreateServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Club_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OpenIMServer.club.club",
	HandlerType: (*ClubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createServer",
			Handler:    _Club_CreateServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "club/club.proto",
}
