// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: club/club.proto

package club

import (
	context "context"
	sdkws "github.com/OpenIMSDK/protocol/sdkws"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManageServer        string `protobuf:"bytes,1,opt,name=manageServer,proto3" json:"manageServer,omitempty"`
	ShareServer         string `protobuf:"bytes,2,opt,name=shareServer,proto3" json:"shareServer,omitempty"`
	ManageMember        string `protobuf:"bytes,3,opt,name=manageMember,proto3" json:"manageMember,omitempty"`
	SendMsg             string `protobuf:"bytes,4,opt,name=sendMsg,proto3" json:"sendMsg,omitempty"`
	ManageMsg           string `protobuf:"bytes,5,opt,name=manageMsg,proto3" json:"manageMsg,omitempty"`
	ManageCommunity     string `protobuf:"bytes,6,opt,name=manageCommunity,proto3" json:"manageCommunity,omitempty"`
	PostTweet           string `protobuf:"bytes,7,opt,name=postTweet,proto3" json:"postTweet,omitempty"`
	TweetReply          string `protobuf:"bytes,8,opt,name=tweetReply,proto3" json:"tweetReply,omitempty"`
	ManageGroupCategory string `protobuf:"bytes,9,opt,name=manageGroupCategory,proto3" json:"manageGroupCategory,omitempty"`
	ManageGroup         string `protobuf:"bytes,10,opt,name=manageGroup,proto3" json:"manageGroup,omitempty"`
}

func (x *RoleAuth) Reset() {
	*x = RoleAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAuth) ProtoMessage() {}

func (x *RoleAuth) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAuth.ProtoReflect.Descriptor instead.
func (*RoleAuth) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{0}
}

func (x *RoleAuth) GetManageServer() string {
	if x != nil {
		return x.ManageServer
	}
	return ""
}

func (x *RoleAuth) GetShareServer() string {
	if x != nil {
		return x.ShareServer
	}
	return ""
}

func (x *RoleAuth) GetManageMember() string {
	if x != nil {
		return x.ManageMember
	}
	return ""
}

func (x *RoleAuth) GetSendMsg() string {
	if x != nil {
		return x.SendMsg
	}
	return ""
}

func (x *RoleAuth) GetManageMsg() string {
	if x != nil {
		return x.ManageMsg
	}
	return ""
}

func (x *RoleAuth) GetManageCommunity() string {
	if x != nil {
		return x.ManageCommunity
	}
	return ""
}

func (x *RoleAuth) GetPostTweet() string {
	if x != nil {
		return x.PostTweet
	}
	return ""
}

func (x *RoleAuth) GetTweetReply() string {
	if x != nil {
		return x.TweetReply
	}
	return ""
}

func (x *RoleAuth) GetManageGroupCategory() string {
	if x != nil {
		return x.ManageGroupCategory
	}
	return ""
}

func (x *RoleAuth) GetManageGroup() string {
	if x != nil {
		return x.ManageGroup
	}
	return ""
}

type CreateServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID             string `protobuf:"bytes,1,opt,name=serverID,proto3" json:"serverID,omitempty"`
	ServerName           string `protobuf:"bytes,2,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Icon                 string `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description          string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Banner               string `protobuf:"bytes,5,opt,name=banner,proto3" json:"banner,omitempty"`
	ApplyMode            int32  `protobuf:"varint,6,opt,name=applyMode,proto3" json:"applyMode,omitempty"`
	InviteMode           int32  `protobuf:"varint,7,opt,name=inviteMode,proto3" json:"inviteMode,omitempty"`
	Searchable           int32  `protobuf:"varint,8,opt,name=searchable,proto3" json:"searchable,omitempty"`
	UserMutualAccessible int32  `protobuf:"varint,9,opt,name=userMutualAccessible,proto3" json:"userMutualAccessible,omitempty"`
	Status               int32  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	OwnerUserID          string `protobuf:"bytes,11,opt,name=ownerUserID,proto3" json:"ownerUserID,omitempty"`
	Ex                   string `protobuf:"bytes,12,opt,name=ex,proto3" json:"ex,omitempty"`
}

func (x *CreateServerReq) Reset() {
	*x = CreateServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerReq) ProtoMessage() {}

func (x *CreateServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerReq.ProtoReflect.Descriptor instead.
func (*CreateServerReq) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServerReq) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

func (x *CreateServerReq) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *CreateServerReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateServerReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateServerReq) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *CreateServerReq) GetApplyMode() int32 {
	if x != nil {
		return x.ApplyMode
	}
	return 0
}

func (x *CreateServerReq) GetInviteMode() int32 {
	if x != nil {
		return x.InviteMode
	}
	return 0
}

func (x *CreateServerReq) GetSearchable() int32 {
	if x != nil {
		return x.Searchable
	}
	return 0
}

func (x *CreateServerReq) GetUserMutualAccessible() int32 {
	if x != nil {
		return x.UserMutualAccessible
	}
	return 0
}

func (x *CreateServerReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateServerReq) GetOwnerUserID() string {
	if x != nil {
		return x.OwnerUserID
	}
	return ""
}

func (x *CreateServerReq) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

type CreateServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateServerResp) Reset() {
	*x = CreateServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerResp) ProtoMessage() {}

func (x *CreateServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerResp.ProtoReflect.Descriptor instead.
func (*CreateServerResp) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{2}
}

type CreateGroupCategoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID     string `protobuf:"bytes,1,opt,name=serverID,proto3" json:"serverID,omitempty"`
	CategoryName string `protobuf:"bytes,2,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	OwnerUserID  string `protobuf:"bytes,3,opt,name=ownerUserID,proto3" json:"ownerUserID,omitempty"`
}

func (x *CreateGroupCategoryReq) Reset() {
	*x = CreateGroupCategoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupCategoryReq) ProtoMessage() {}

func (x *CreateGroupCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupCategoryReq.ProtoReflect.Descriptor instead.
func (*CreateGroupCategoryReq) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupCategoryReq) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

func (x *CreateGroupCategoryReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CreateGroupCategoryReq) GetOwnerUserID() string {
	if x != nil {
		return x.OwnerUserID
	}
	return ""
}

type CreateGroupCategoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateGroupCategoryResp) Reset() {
	*x = CreateGroupCategoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupCategoryResp) ProtoMessage() {}

func (x *CreateGroupCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupCategoryResp.ProtoReflect.Descriptor instead.
func (*CreateGroupCategoryResp) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{4}
}

type GetServerRecommendedListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetServerRecommendedListReq) Reset() {
	*x = GetServerRecommendedListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerRecommendedListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRecommendedListReq) ProtoMessage() {}

func (x *GetServerRecommendedListReq) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRecommendedListReq.ProtoReflect.Descriptor instead.
func (*GetServerRecommendedListReq) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{5}
}

type GetServerRecommendecListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servers []*sdkws.ServerFullInfo `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (x *GetServerRecommendecListResp) Reset() {
	*x = GetServerRecommendecListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerRecommendecListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRecommendecListResp) ProtoMessage() {}

func (x *GetServerRecommendecListResp) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRecommendecListResp.ProtoReflect.Descriptor instead.
func (*GetServerRecommendecListResp) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{6}
}

func (x *GetServerRecommendecListResp) GetServers() []*sdkws.ServerFullInfo {
	if x != nil {
		return x.Servers
	}
	return nil
}

type GetJoinedServerListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *GetJoinedServerListReq) Reset() {
	*x = GetJoinedServerListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJoinedServerListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinedServerListReq) ProtoMessage() {}

func (x *GetJoinedServerListReq) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinedServerListReq.ProtoReflect.Descriptor instead.
func (*GetJoinedServerListReq) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{7}
}

func (x *GetJoinedServerListReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetJoinedServerListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servers []*sdkws.ServersListInfo `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (x *GetJoinedServerListResp) Reset() {
	*x = GetJoinedServerListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJoinedServerListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinedServerListResp) ProtoMessage() {}

func (x *GetJoinedServerListResp) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinedServerListResp.ProtoReflect.Descriptor instead.
func (*GetJoinedServerListResp) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{8}
}

func (x *GetJoinedServerListResp) GetServers() []*sdkws.ServersListInfo {
	if x != nil {
		return x.Servers
	}
	return nil
}

type GetServerDetailsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID string `protobuf:"bytes,1,opt,name=serverID,proto3" json:"serverID,omitempty"`
}

func (x *GetServerDetailsReq) Reset() {
	*x = GetServerDetailsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerDetailsReq) ProtoMessage() {}

func (x *GetServerDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerDetailsReq.ProtoReflect.Descriptor instead.
func (*GetServerDetailsReq) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{9}
}

func (x *GetServerDetailsReq) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

type GetServerDetailsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server       *sdkws.ServerFullInfo          `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	CategoryList []*sdkws.GroupCategoryListInfo `protobuf:"bytes,2,rep,name=categoryList,proto3" json:"categoryList,omitempty"`
	Joined       bool                           `protobuf:"varint,3,opt,name=joined,proto3" json:"joined,omitempty"`
}

func (x *GetServerDetailsResp) Reset() {
	*x = GetServerDetailsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerDetailsResp) ProtoMessage() {}

func (x *GetServerDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerDetailsResp.ProtoReflect.Descriptor instead.
func (*GetServerDetailsResp) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{10}
}

func (x *GetServerDetailsResp) GetServer() *sdkws.ServerFullInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *GetServerDetailsResp) GetCategoryList() []*sdkws.GroupCategoryListInfo {
	if x != nil {
		return x.CategoryList
	}
	return nil
}

func (x *GetServerDetailsResp) GetJoined() bool {
	if x != nil {
		return x.Joined
	}
	return false
}

type DeleteServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerIDList []string `protobuf:"bytes,1,rep,name=serverIDList,proto3" json:"serverIDList,omitempty"`
}

func (x *DeleteServerReq) Reset() {
	*x = DeleteServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerReq) ProtoMessage() {}

func (x *DeleteServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerReq.ProtoReflect.Descriptor instead.
func (*DeleteServerReq) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteServerReq) GetServerIDList() []string {
	if x != nil {
		return x.ServerIDList
	}
	return nil
}

type DeleteServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteServerResp) Reset() {
	*x = DeleteServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerResp) ProtoMessage() {}

func (x *DeleteServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerResp.ProtoReflect.Descriptor instead.
func (*DeleteServerResp) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{12}
}

type JoinServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID      string `protobuf:"bytes,1,opt,name=serverID,proto3" json:"serverID,omitempty"`
	ReqMessage    string `protobuf:"bytes,2,opt,name=reqMessage,proto3" json:"reqMessage,omitempty"`
	JoinSource    int32  `protobuf:"varint,3,opt,name=joinSource,proto3" json:"joinSource,omitempty"`
	UserID        string `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	InvitedUserID string `protobuf:"bytes,5,opt,name=invitedUserID,proto3" json:"invitedUserID,omitempty"`
}

func (x *JoinServerReq) Reset() {
	*x = JoinServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinServerReq) ProtoMessage() {}

func (x *JoinServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinServerReq.ProtoReflect.Descriptor instead.
func (*JoinServerReq) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{13}
}

func (x *JoinServerReq) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

func (x *JoinServerReq) GetReqMessage() string {
	if x != nil {
		return x.ReqMessage
	}
	return ""
}

func (x *JoinServerReq) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *JoinServerReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *JoinServerReq) GetInvitedUserID() string {
	if x != nil {
		return x.InvitedUserID
	}
	return ""
}

type JoinServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinServerResp) Reset() {
	*x = JoinServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinServerResp) ProtoMessage() {}

func (x *JoinServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinServerResp.ProtoReflect.Descriptor instead.
func (*JoinServerResp) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{14}
}

type QuitServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID string `protobuf:"bytes,1,opt,name=serverID,proto3" json:"serverID,omitempty"`
	UserID   string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *QuitServerReq) Reset() {
	*x = QuitServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitServerReq) ProtoMessage() {}

func (x *QuitServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitServerReq.ProtoReflect.Descriptor instead.
func (*QuitServerReq) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{15}
}

func (x *QuitServerReq) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

func (x *QuitServerReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type QuitServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuitServerResp) Reset() {
	*x = QuitServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitServerResp) ProtoMessage() {}

func (x *QuitServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitServerResp.ProtoReflect.Descriptor instead.
func (*QuitServerResp) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{16}
}

var File_club_club_proto protoreflect.FileDescriptor

var file_club_club_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6c, 0x75, 0x62, 0x2f, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x63, 0x6c, 0x75, 0x62, 0x1a, 0x11, 0x73, 0x64, 0x6b, 0x77, 0x73, 0x2f, 0x73, 0x64, 0x6b, 0x77,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe8, 0x02, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65,
	0x41, 0x75, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x4d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x74, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30,
	0x0a, 0x13, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x22, 0xf7, 0x02, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x32,
	0x0a, 0x14, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x75, 0x73,
	0x65, 0x72, 0x4d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x62,
	0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02,
	0x65, 0x78, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x65, 0x78, 0x22, 0x12, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x7a, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x19, 0x0a, 0x17,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x5c, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x63, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x64, 0x6b, 0x77, 0x73, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x65,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x58, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x69,
	0x6e, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3d, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x73, 0x64, 0x6b, 0x77, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x22, 0x31, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x44, 0x22, 0xb9, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x06,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x4f,
	0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x64, 0x6b, 0x77,
	0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x4d, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x64,
	0x6b, 0x77, 0x73, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x6f, 0x69, 0x6e, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x22,
	0x35, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0xa9, 0x01, 0x0a, 0x0d, 0x4a,
	0x6f, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x71, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6a, 0x6f, 0x69, 0x6e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6a, 0x6f,
	0x69, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x10, 0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x43, 0x0a, 0x0d, 0x51, 0x75, 0x69, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x10, 0x0a,
	0x0e, 0x51, 0x75, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x32,
	0xa2, 0x06, 0x0a, 0x04, 0x63, 0x6c, 0x75, 0x62, 0x12, 0x57, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49,
	0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x4f,
	0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x7b, 0x0a, 0x18, 0x67, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x2e,
	0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x2f, 0x2e,
	0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x65, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x6c,
	0x0a, 0x13, 0x67, 0x65, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x69,
	0x6e, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x2a, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x63, 0x6c, 0x75, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x63, 0x0a, 0x10,
	0x67, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x26, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x63, 0x6c, 0x75, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49,
	0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x51, 0x0a, 0x0a, 0x6a, 0x6f, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x20, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63,
	0x6c, 0x75, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x21, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x0a, 0x71, 0x75, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x20, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5d, 0x0a, 0x12, 0x62, 0x61, 0x74, 0x63, 0x68,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x22, 0x2e,
	0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75,
	0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x23, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x6c, 0x0a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x29, 0x2e,
	0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75,
	0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x2a, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x49,
	0x4d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x53, 0x44, 0x4b, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6c, 0x75, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_club_club_proto_rawDescOnce sync.Once
	file_club_club_proto_rawDescData = file_club_club_proto_rawDesc
)

func file_club_club_proto_rawDescGZIP() []byte {
	file_club_club_proto_rawDescOnce.Do(func() {
		file_club_club_proto_rawDescData = protoimpl.X.CompressGZIP(file_club_club_proto_rawDescData)
	})
	return file_club_club_proto_rawDescData
}

var file_club_club_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_club_club_proto_goTypes = []interface{}{
	(*RoleAuth)(nil),                     // 0: OpenIMServer.club.RoleAuth
	(*CreateServerReq)(nil),              // 1: OpenIMServer.club.CreateServerReq
	(*CreateServerResp)(nil),             // 2: OpenIMServer.club.CreateServerResp
	(*CreateGroupCategoryReq)(nil),       // 3: OpenIMServer.club.CreateGroupCategoryReq
	(*CreateGroupCategoryResp)(nil),      // 4: OpenIMServer.club.CreateGroupCategoryResp
	(*GetServerRecommendedListReq)(nil),  // 5: OpenIMServer.club.GetServerRecommendedListReq
	(*GetServerRecommendecListResp)(nil), // 6: OpenIMServer.club.GetServerRecommendecListResp
	(*GetJoinedServerListReq)(nil),       // 7: OpenIMServer.club.GetJoinedServerListReq
	(*GetJoinedServerListResp)(nil),      // 8: OpenIMServer.club.GetJoinedServerListResp
	(*GetServerDetailsReq)(nil),          // 9: OpenIMServer.club.GetServerDetailsReq
	(*GetServerDetailsResp)(nil),         // 10: OpenIMServer.club.GetServerDetailsResp
	(*DeleteServerReq)(nil),              // 11: OpenIMServer.club.DeleteServerReq
	(*DeleteServerResp)(nil),             // 12: OpenIMServer.club.DeleteServerResp
	(*JoinServerReq)(nil),                // 13: OpenIMServer.club.JoinServerReq
	(*JoinServerResp)(nil),               // 14: OpenIMServer.club.JoinServerResp
	(*QuitServerReq)(nil),                // 15: OpenIMServer.club.QuitServerReq
	(*QuitServerResp)(nil),               // 16: OpenIMServer.club.QuitServerResp
	(*sdkws.ServerFullInfo)(nil),         // 17: OpenIMServer.sdkws.ServerFullInfo
	(*sdkws.ServersListInfo)(nil),        // 18: OpenIMServer.sdkws.ServersListInfo
	(*sdkws.GroupCategoryListInfo)(nil),  // 19: OpenIMServer.sdkws.GroupCategoryListInfo
}
var file_club_club_proto_depIdxs = []int32{
	17, // 0: OpenIMServer.club.GetServerRecommendecListResp.servers:type_name -> OpenIMServer.sdkws.ServerFullInfo
	18, // 1: OpenIMServer.club.GetJoinedServerListResp.servers:type_name -> OpenIMServer.sdkws.ServersListInfo
	17, // 2: OpenIMServer.club.GetServerDetailsResp.server:type_name -> OpenIMServer.sdkws.ServerFullInfo
	19, // 3: OpenIMServer.club.GetServerDetailsResp.categoryList:type_name -> OpenIMServer.sdkws.GroupCategoryListInfo
	1,  // 4: OpenIMServer.club.club.createServer:input_type -> OpenIMServer.club.CreateServerReq
	5,  // 5: OpenIMServer.club.club.getServerRecommendedList:input_type -> OpenIMServer.club.GetServerRecommendedListReq
	7,  // 6: OpenIMServer.club.club.getJoinedServerList:input_type -> OpenIMServer.club.GetJoinedServerListReq
	9,  // 7: OpenIMServer.club.club.getServerDetails:input_type -> OpenIMServer.club.GetServerDetailsReq
	13, // 8: OpenIMServer.club.club.joinServer:input_type -> OpenIMServer.club.JoinServerReq
	15, // 9: OpenIMServer.club.club.quitServer:input_type -> OpenIMServer.club.QuitServerReq
	11, // 10: OpenIMServer.club.club.batchDeleteServers:input_type -> OpenIMServer.club.DeleteServerReq
	3,  // 11: OpenIMServer.club.club.createGroupCategory:input_type -> OpenIMServer.club.CreateGroupCategoryReq
	2,  // 12: OpenIMServer.club.club.createServer:output_type -> OpenIMServer.club.CreateServerResp
	6,  // 13: OpenIMServer.club.club.getServerRecommendedList:output_type -> OpenIMServer.club.GetServerRecommendecListResp
	8,  // 14: OpenIMServer.club.club.getJoinedServerList:output_type -> OpenIMServer.club.GetJoinedServerListResp
	10, // 15: OpenIMServer.club.club.getServerDetails:output_type -> OpenIMServer.club.GetServerDetailsResp
	14, // 16: OpenIMServer.club.club.joinServer:output_type -> OpenIMServer.club.JoinServerResp
	16, // 17: OpenIMServer.club.club.quitServer:output_type -> OpenIMServer.club.QuitServerResp
	12, // 18: OpenIMServer.club.club.batchDeleteServers:output_type -> OpenIMServer.club.DeleteServerResp
	4,  // 19: OpenIMServer.club.club.createGroupCategory:output_type -> OpenIMServer.club.CreateGroupCategoryResp
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_club_club_proto_init() }
func file_club_club_proto_init() {
	if File_club_club_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_club_club_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupCategoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupCategoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerRecommendedListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerRecommendecListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJoinedServerListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJoinedServerListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerDetailsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerDetailsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_club_club_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_club_club_proto_goTypes,
		DependencyIndexes: file_club_club_proto_depIdxs,
		MessageInfos:      file_club_club_proto_msgTypes,
	}.Build()
	File_club_club_proto = out.File
	file_club_club_proto_rawDesc = nil
	file_club_club_proto_goTypes = nil
	file_club_club_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClubClient is the client API for Club service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClubClient interface {
	// 创建部落
	CreateServer(ctx context.Context, in *CreateServerReq, opts ...grpc.CallOption) (*CreateServerResp, error)
	// 获取部落列表
	GetServerRecommendedList(ctx context.Context, in *GetServerRecommendedListReq, opts ...grpc.CallOption) (*GetServerRecommendecListResp, error)
	// 获取加入的部落列表
	GetJoinedServerList(ctx context.Context, in *GetJoinedServerListReq, opts ...grpc.CallOption) (*GetJoinedServerListResp, error)
	// 获取部落详情
	GetServerDetails(ctx context.Context, in *GetServerDetailsReq, opts ...grpc.CallOption) (*GetServerDetailsResp, error)
	// 加入部落
	JoinServer(ctx context.Context, in *JoinServerReq, opts ...grpc.CallOption) (*JoinServerResp, error)
	// 退出部落
	QuitServer(ctx context.Context, in *QuitServerReq, opts ...grpc.CallOption) (*QuitServerResp, error)
	// 删除部落
	BatchDeleteServers(ctx context.Context, in *DeleteServerReq, opts ...grpc.CallOption) (*DeleteServerResp, error)
	// 创建分组
	CreateGroupCategory(ctx context.Context, in *CreateGroupCategoryReq, opts ...grpc.CallOption) (*CreateGroupCategoryResp, error)
}

type clubClient struct {
	cc grpc.ClientConnInterface
}

func NewClubClient(cc grpc.ClientConnInterface) ClubClient {
	return &clubClient{cc}
}

func (c *clubClient) CreateServer(ctx context.Context, in *CreateServerReq, opts ...grpc.CallOption) (*CreateServerResp, error) {
	out := new(CreateServerResp)
	err := c.cc.Invoke(ctx, "/OpenIMServer.club.club/createServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) GetServerRecommendedList(ctx context.Context, in *GetServerRecommendedListReq, opts ...grpc.CallOption) (*GetServerRecommendecListResp, error) {
	out := new(GetServerRecommendecListResp)
	err := c.cc.Invoke(ctx, "/OpenIMServer.club.club/getServerRecommendedList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) GetJoinedServerList(ctx context.Context, in *GetJoinedServerListReq, opts ...grpc.CallOption) (*GetJoinedServerListResp, error) {
	out := new(GetJoinedServerListResp)
	err := c.cc.Invoke(ctx, "/OpenIMServer.club.club/getJoinedServerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) GetServerDetails(ctx context.Context, in *GetServerDetailsReq, opts ...grpc.CallOption) (*GetServerDetailsResp, error) {
	out := new(GetServerDetailsResp)
	err := c.cc.Invoke(ctx, "/OpenIMServer.club.club/getServerDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) JoinServer(ctx context.Context, in *JoinServerReq, opts ...grpc.CallOption) (*JoinServerResp, error) {
	out := new(JoinServerResp)
	err := c.cc.Invoke(ctx, "/OpenIMServer.club.club/joinServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) QuitServer(ctx context.Context, in *QuitServerReq, opts ...grpc.CallOption) (*QuitServerResp, error) {
	out := new(QuitServerResp)
	err := c.cc.Invoke(ctx, "/OpenIMServer.club.club/quitServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) BatchDeleteServers(ctx context.Context, in *DeleteServerReq, opts ...grpc.CallOption) (*DeleteServerResp, error) {
	out := new(DeleteServerResp)
	err := c.cc.Invoke(ctx, "/OpenIMServer.club.club/batchDeleteServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) CreateGroupCategory(ctx context.Context, in *CreateGroupCategoryReq, opts ...grpc.CallOption) (*CreateGroupCategoryResp, error) {
	out := new(CreateGroupCategoryResp)
	err := c.cc.Invoke(ctx, "/OpenIMServer.club.club/createGroupCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClubServer is the server API for Club service.
type ClubServer interface {
	// 创建部落
	CreateServer(context.Context, *CreateServerReq) (*CreateServerResp, error)
	// 获取部落列表
	GetServerRecommendedList(context.Context, *GetServerRecommendedListReq) (*GetServerRecommendecListResp, error)
	// 获取加入的部落列表
	GetJoinedServerList(context.Context, *GetJoinedServerListReq) (*GetJoinedServerListResp, error)
	// 获取部落详情
	GetServerDetails(context.Context, *GetServerDetailsReq) (*GetServerDetailsResp, error)
	// 加入部落
	JoinServer(context.Context, *JoinServerReq) (*JoinServerResp, error)
	// 退出部落
	QuitServer(context.Context, *QuitServerReq) (*QuitServerResp, error)
	// 删除部落
	BatchDeleteServers(context.Context, *DeleteServerReq) (*DeleteServerResp, error)
	// 创建分组
	CreateGroupCategory(context.Context, *CreateGroupCategoryReq) (*CreateGroupCategoryResp, error)
}

// UnimplementedClubServer can be embedded to have forward compatible implementations.
type UnimplementedClubServer struct {
}

func (*UnimplementedClubServer) CreateServer(context.Context, *CreateServerReq) (*CreateServerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServer not implemented")
}
func (*UnimplementedClubServer) GetServerRecommendedList(context.Context, *GetServerRecommendedListReq) (*GetServerRecommendecListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerRecommendedList not implemented")
}
func (*UnimplementedClubServer) GetJoinedServerList(context.Context, *GetJoinedServerListReq) (*GetJoinedServerListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJoinedServerList not implemented")
}
func (*UnimplementedClubServer) GetServerDetails(context.Context, *GetServerDetailsReq) (*GetServerDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerDetails not implemented")
}
func (*UnimplementedClubServer) JoinServer(context.Context, *JoinServerReq) (*JoinServerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinServer not implemented")
}
func (*UnimplementedClubServer) QuitServer(context.Context, *QuitServerReq) (*QuitServerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitServer not implemented")
}
func (*UnimplementedClubServer) BatchDeleteServers(context.Context, *DeleteServerReq) (*DeleteServerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteServers not implemented")
}
func (*UnimplementedClubServer) CreateGroupCategory(context.Context, *CreateGroupCategoryReq) (*CreateGroupCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroupCategory not implemented")
}

func RegisterClubServer(s *grpc.Server, srv ClubServer) {
	s.RegisterService(&_Club_serviceDesc, srv)
}

func _Club_CreateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).CreateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenIMServer.club.club/CreateServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).CreateServer(ctx, req.(*CreateServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_GetServerRecommendedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerRecommendedListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).GetServerRecommendedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenIMServer.club.club/GetServerRecommendedList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).GetServerRecommendedList(ctx, req.(*GetServerRecommendedListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_GetJoinedServerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJoinedServerListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).GetJoinedServerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenIMServer.club.club/GetJoinedServerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).GetJoinedServerList(ctx, req.(*GetJoinedServerListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_GetServerDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerDetailsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).GetServerDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenIMServer.club.club/GetServerDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).GetServerDetails(ctx, req.(*GetServerDetailsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_JoinServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).JoinServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenIMServer.club.club/JoinServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).JoinServer(ctx, req.(*JoinServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_QuitServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).QuitServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenIMServer.club.club/QuitServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).QuitServer(ctx, req.(*QuitServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_BatchDeleteServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).BatchDeleteServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenIMServer.club.club/BatchDeleteServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).BatchDeleteServers(ctx, req.(*DeleteServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_CreateGroupCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).CreateGroupCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenIMServer.club.club/CreateGroupCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).CreateGroupCategory(ctx, req.(*CreateGroupCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Club_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OpenIMServer.club.club",
	HandlerType: (*ClubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createServer",
			Handler:    _Club_CreateServer_Handler,
		},
		{
			MethodName: "getServerRecommendedList",
			Handler:    _Club_GetServerRecommendedList_Handler,
		},
		{
			MethodName: "getJoinedServerList",
			Handler:    _Club_GetJoinedServerList_Handler,
		},
		{
			MethodName: "getServerDetails",
			Handler:    _Club_GetServerDetails_Handler,
		},
		{
			MethodName: "joinServer",
			Handler:    _Club_JoinServer_Handler,
		},
		{
			MethodName: "quitServer",
			Handler:    _Club_QuitServer_Handler,
		},
		{
			MethodName: "batchDeleteServers",
			Handler:    _Club_BatchDeleteServers_Handler,
		},
		{
			MethodName: "createGroupCategory",
			Handler:    _Club_CreateGroupCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "club/club.proto",
}
